#!/bin/sh
run() {
    if ! pgrep "$1" >/dev/null; then
        "$@" &
    fi
}

xrdb -merge ~/.config/x11/Xresources &
xrdbpid=$!

eval "$(gnome-keyring-daemon --start)"
export SSH_AUTH_SOCK

if [ "$(uname -n)" = "skynet" ]; then
    run multi-monitor
    run kmonad-refresh &
    run /usr/bin/emacs --daemon &
    run /usr/bin/pipewire &
    run pacmac-tray &
    run sxhkd &
    run dm-wacom &
    run picom -b &
    run clipmenud &
    run redshift &
    run lxsession &
    run mpd &
    run dunst-reload &
    run "$HOME"/.fehbg &
    xsetroot -cursor_name left_ptr
fi

run syncthing-gtk --minimized &

[ -n "$xrdbpid" ] && wait "$xrdbpid"
