#!/bin/sh
if [ "$(uname -n)" = "gpdskynet" ]; then
	# unclutter --hide-on-touch
	xrdb -merge ~/.config/x11/Xresources.d/gpdskynet.xresources
  # xinput map-to-output "pointer:Goodix Capacitive TouchScreen" DSI-1-1

elif [ "$(uname -n)" = "skynet" ]; then
	xrdb -merge ~/.config/x11/Xresources.d/skynet.xresources
 
elif [ "$(uname -n)" = "ArchKeith" ]; then
	xrdb -merge ~/.config/x11/Xresources.d/archkeith.xresources
fi

xrdb -merge ~/.config/x11/Xresources

# multi-monitor

# eval "$(gnome-keyring-daemon --start)"
export SSH_AUTH_SOCK

kmonad-refresh &
sxhkd &
# nm-applet &
# picom -b &
# clipcatd &
# redshift &
# lxsession &

# dunst-reload &
xsetroot -cursor_name left_ptr

syncthing-gtk --minimized &
