#!/bin/sh
run() {
	if ! pgrep "$1" >/dev/null; then
		"$@" &
	fi
}


if [ "$(uname -n)" = "gpdskynet" ]; then
	run unclutter --hide-on-touch
	xrdb -merge ~/.config/x11/Xresources.d/gpdskynet.xresources
  xinput map-to-output "pointer:Goodix Capacitive TouchScreen" DSI-1-1

elif [ "$(uname -n)" = "skynet" ]; then
	xrdb -merge ~/.config/x11/Xresources.d/skynet.xresources
 
elif [ "$(uname -n)" = "ArchKeith" ]; then
	xrdb -merge ~/.config/x11/Xresources.d/archkeith.xresources
fi

xrdb -merge ~/.config/x11/Xresources

multi-monitor

eval "$(gnome-keyring-daemon --start)"
export SSH_AUTH_SOCK

run kmonad-refresh &
run sxhkd &
run nm-applet &
run otd &
run picom -b &
run clipcatd &
run redshift &
run lxsession &

run dunst-reload &
xsetroot -cursor_name left_ptr

run syncthing-gtk --minimized &

# Don't Randomly Turn off
xset s off
xset -dpms
xset s noblank
