#+title: Sxhkdrc
#+property: header-args :tangle sxhkdrc :async conf
#+auto_tangle: t

#+begin_src conf
# -*- conf -*-
#+end_src

* Table of Contents :toc:
- [[#sxhkd][Sxhkd]]
- [[#frequent-bindings][Frequent Bindings]]
- [[#super--space-followed-by-o-opening][=Super + space= followed by =O=, opening.]]
- [[#super--space-followed-by-p-dmenu-scripts][=Super + space= followed by =p=, dmenu scripts.]]
- [[#super--space-followed-by--system-bindings][=Super + space= followed by =;=, system bindings]]
- [[#xf86-bindings][XF86 Bindings]]
- [[#media-control][Media control]]
- [[#super--function-keys][=super += function keys]]

* Sxhkd

My =sxhkd= bindings, mostly revolving around the =super + space= leader key. I find
it more ergonomic than holding =super= and then pressing another key to launch
other applications. This also frees up keys for window manager control key
bindings.

This is to provide a helper function

#+begin_src conf
# Show sxhkd keybindings in dmenu
super + slash
        sxhkd-help
#+end_src

* Frequent Bindings

These are keybindings which one uses the most. Thus we want as fewer key-presses as possible

#+begin_src conf
# Open desktop applications
super + space ; space
      emacsclient -e '(counsel-linux-app)'

# Dmenu run executables
super + space ; d
      emacsclient -e '(dmenu)'

# Open terminal emulator
super + space ; t
      samedirall $TERMINAL

# Open lf file manager
super + space ; r
      samedirall $TERMINAL -e lf

# Open ncmpcpp music player
super + space ; n
      pidof ncmpcpp || $TERMINAL -e ncmpcpp

# Dmenu list opened windows
super + space ; b
      emacsclient -e '(ibuffer)'

# Open Firefox
super + space ; w
      pidof firefox >/dev/null && wmctrl -lx | awk '$3 ~ "Firefox" {print $1}' | head -1 | xargs -r xdotool windowactivate || firefox

# Open Chromium
super + space ; c
      pidof chromium >/dev/null && wmctrl -lx | awk '$3 ~ "Chromium" {print $1}' | head -1 | xargs -r xdotool windowactivate || chromium

# Toggle mute microphone
super + space ; m
      mic-toggle
#+end_src

* =Super + space= followed by =O=, opening.

Those are for opening common applications by pressing =super + space= and then =o=
followed by another key, depending on the application one wants to open.

#+begin_src conf
# Open Discord
super + space ; o ; d
      which prime-run && prime-run discord || discord

# Open FTB Launcher
super + space ; o ; f
      /media/FTBA/FTBApp

# Open VSCodium
super + space ; o ; v
      which prime-run && prime-run vscodium || vscodium

# Open zotero
super + space ; o ; t
      pidof zotero >/dev/null && wmctrl -lx | awk '$3 ~ "Zotero" {print $1}' | head -1 | xargs -r xdotool windowactivate || zotero

# Open Zoom
super + space ; o ; z
      zoom
#+end_src

* =Super + space= followed by =p=, dmenu scripts.

These are the dmenu scripts.

#+begin_src conf
# Dmenu Man pages
super + space ; p ; a
      dm-man

# Dmenu Clipmenu clipboard manager
super + space ; p ; c
      clipmenu

# Dmenu Open terminal in directory
super + space ; p ; d
      dm-directory

# Dmenu Change colorscheme
super + space ; p ; shift + c
      dm-colorscheme

# Dmenu Emoji selector to clipboard
super + space ; p ; e
      dm-emoji

# Dmenu kill application
super + space ; p ; k
      dm-kill

# Dmenu Buku bookmark manager opener
super + space ; p ; m
      dm-buku

# Dmenu Mount drives
super + space ; p ; o
      dm-mount

# Dmenu Passmenu passwords to clipboard
super + space ; p ; p
      dm-passmenu

# Dmenu Radio fm
super + space ; p ; b
      dm-beats

# Dmenu Open scripts in $EDITOR
super + space ; p ; s
      dm-scripts

# Dmenu Unmount drives
super + space ; p ; u
      dm-umount

# Dmenu Wttr weather forecast
super + space ; p ; w
      weatherforecast
#+end_src

* =Super + space= followed by =;=, system bindings

The bindings relevant to changing wallpapers, opening pulsemixer, etc... Related to system settings.

#+begin_src conf
# Setwallpaper Randomly from "a2n" collection
super + space ; semicolon ; a
      setwallpaper a2n

# Setwallpaper Randomly from "dt" collection
super + space ; semicolon ; d
      setwallpaper dt

# Setwallpaper Randomly from personal collection
super + space ; semicolon ; e
      setwallpaper elyk

# Open pulsemixer volume manager
super + space ; semicolon ; v
      $TERMINAL -e pulsemixer

# Interactively setwallpaper using nsxiv
super + space ; semicolon ; w
      nsxiv -rqto $XDG_PICTURES_DIR/wallpapers/*

# Dmenu system activity
super + Escape
      sysact
#+end_src

* XF86 Bindings

Bindings related to the =Fn= key.

#+begin_src conf
# {Increase,Decrease} brightness
XF86MonBrightness{Up,Down}
      brightness {up,down}

# {Increase,Decrease} volume
XF86Audio{Raise,Lower}Volume
      volume {up,down}

# Mute/Unmute volume
XF86AudioMute
      volume mute

# Mute/Unmute microphone
XF86AudioMicMute
      mic-toggle

XF86Audio{Prev,Next,Play}
    playerctl {previous,next,play-pause}

# Take screenshot of selection
Print ; s
      maimpick 'Selected'

# Take screenshot of current screen
Print ; c
      maimpick 'Current'

# Take screenshot of whole desktop
Print ; f
      maimpick 'Fullscreen'

# Take screenshot of selection into clipboard
Print ; shift + s
      maimpick 'Selected (copy)'

# Take screenshot of current screen into clipboard
Print ; shift + c
      maimpick 'Current (copy)'

# Take screenshot of whole desktop into clipboard
Print ; shift + f
      maimpick 'Fullscreen (copy)'
#+end_src

* Media control

For media and music control, one does not want the leader key to be used, since
one does not desire added delay when changing songs or volume.

#+begin_src conf
# MPC Move backwards 10 secs
super + comma
      mpc seek -10

# MPC Move forwards 10 secs
super + period
      mpc seek +10

# MPC Previous song
super + bracketleft
      mpc prev

# MPC Next song
super + bracketright
      mpc next

# MPC Restart song
super + shift + bracketleft
      mpc seek 0%

# MPC {Increase,Decrease} volume by 2
super + {equal,minus}
      mpc volume {+,-}2 && mpc-volume

# MPC Play/pause song
super + p
      mpc toggle
#+end_src

* =super += function keys

#+begin_src conf
# Toggle Buckle spring keyboard sound effect
super + F2
      buckle-spring

# Refresh doom configuration and restart the emacs daemon
#super + F3
#      restart-emacs

# Refresh kmonad configuration
super + F4
      notify-send "Refreshing KMonad in 2 secs"; kmonad-refresh; notify-send "Success!"
#+end_src

