#! /bin/sh

pgrep -x sxhkd && pkill -SIGUSR1 sxhkd || setsid -f sxhkd

bspc monitor eDP1 -d 一. 二. 三.
bspc monitor HDMI-1-0 -d 四. 五.

# 一. 二. 三. 四. 五. 六. 七. 八. 九.

bspc config border_width            2
bspc config window_gap              12
bspc config focus_follows_pointer   true
bspc config swallow_first_click     true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus   false

bspc config ignore_ewmh_focus       true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
