#! /bin/sh

#pgrep -x sxhkd && pkill -SIGUSR1 sxhkd || setsid -f sxhkd

bspc monitor eDP1     -d 1 3 4 5 6 7 8
bspc monitor HDMI-1-0 -d 2

# 一. 二. 三. 四. 五. 六. 七. 八. 九.

bspc config border_width            2
bspc config window_gap              12
bspc config focus_follows_pointer   true
bspc config swallow_first_click     true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus   false

bspc config ignore_ewmh_focus       true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Chromium desktop='2'
bspc rule -a firefox desktop='2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

bspc rule -a "*:Toolkit:Picture-in-Picture" \
     state=floating sticky=on follow=off focus=on

bspc config focused_border_color "$(xrdb -get color4)"
bspc config normal_border_color "$(xrdb -get background)"
bspc config active_border_color "$(xrdb -get background)"
bspc config presel_feedback_color "$(xrdb -get color6)"

"$HOME"/.config/polybar/launch.sh
