#!/bin/bash

choice=$(printf "%s\n" "SINGLE" "DUAL" "TV" | dmenu -p "Which mode?")

if [ $choice = "DUAL" ]; then
	direction=$(printf "%s\n" "Right" "Left" | dmenu -p "Where to attach?")
	case $direction in
	"Right") args="--right-of" ;;
	"Left") args="--left-of" ;;
	esac
fi

if [ "$(uname -n)" = skynet ]; then
	xrandr_single() { xrandr --output eDP1 --auto --output HDMI-1-0 --off; }
  xrandr_dual() { xrandr --output eDP1 --primary --auto --output HDMI-1-0 --auto $args eDP1 --set "PRIME Synchronization" 1; }
  xrandr_tv() { xrandr --output eDP1 --off --output HDMI-1-0 --auto --set "PRIME Synchronization" 1; }
else
	xrandr_single() { xrandr --output DSI1 --auto --output HDMI1 --off; }
  xrandr_dual() { xrandr --output DSI1 --primary --auto --output HDMI1 --auto $args DSI1; }
fi

case $choice in
"SINGLE") xrandr_single & ;;
"DUAL") xrandr_dual & ;;
"TV") xrandr_tv & ;;
esac

herbstclient detect_monitors

feh $HOME/.fehbg &
