#!/bin/sh

get_browser() { printf "Firefox:: \nChromium:: "; }
launch() {
	while ! wmctrl -a "$@" 2>/dev/null; do
    sleep 1
  done
}

URL="https://www.startpage.com/sp/search?query="
QUERY=$(get_browser | rofi-dmenu -p "Search:" | tr '[:upper:]' '[:lower:]')

if [ -z "$QUERY" ]; then
	exit 1
fi

WEBB=$(echo "$QUERY" | awk -F":: " '{print $1}')
SEARCHED=$(echo "$QUERY" | awk -F":: " '{print $2}')

case "$SEARCHED" in
"")
	setsid -f $BROWSER "${URL}${QUERY}" 2>/dev/null
  launch "$BROWSER"
	;;
*)
	setsid -f $WEBB "${URL}${SEARCHED}" 2>/dev/null
  launch "$WEBB"
	;;
esac
