#!/bin/sh
# A dmenu wrapper script for system functions.
#

logout_menu() {
	printf "%s\n" \
		"1.  Refresh sxhkd" \
		"2.  Reboot" \
		"3.  Shutdown" |
		rofi-dmenu -l 6 -p 'Action: '
}

case "$(readlink -f /sbin/init)" in
	*systemd*) ctl='systemctl' ;;
	*) ctl='loginctl' ;;
esac

case $(logout_menu | awk -F"." '{print $1}') in
	"1") pgrep sxhkd && pkill -SIGUSR1 sxhkd || setsid -f sh -c "sxhkd" ;;
	"2") $ctl reboot -i ;;
	"3") $ctl poweroff -i ;;
	*) exit 1 ;;
esac
