color_bg="default"
color_fg="colour15"
color_green="colour2"
color_yellow="colour3"
color_red="colour1"
color_blue="colour4"
color_cyan="colour6"
color_purple="colour5"
color_gray="colour8"
color_selection="colour7"

source "$tmux_conf_dir/skin_shared.tmux"
