#!/bin/sh

MONITOR="ddcci8"

# Increment to use.
cur=$(xbacklight -get)
case "$1" in
"") echo "$cur" ;;
"up")
		brightnessctl --device $MONITOR set +20%;;
"down")
		brightnessctl --device $MONITOR set 20%-;;
"sup")
		brightnessctl --device $MONITOR set +1%;;
"sdown")
		brightnessctl --device $MONITOR set 1%-;;
*)
	echo "Unsupported: \"$1\""
	exit 1
	;;
esac