#!/bin/sh
if pidof buckle; then
	killall buckle && notif=DISABLED
else
	setsid -f buckle -g 100 && notif=ENABLED
fi
dunstify --replace=555 -i  "$HOME/.local/share/icons/bucklespring.png" "Buckle Spring" \
	"$notif"
