#!/bin/sh

if [ $# -lq 3 ]; then
    echo "Usage: "${0}" <i3_mark> <launch_cmd>" "<width_%>" "<height_%>"
    echo "Example: ${0} 'scratch-emacs' 'emacsclient -c -a emacs'" "70" "80"
    exit 1
fi

I3_MARK=${1}
LAUNCH_CMD=${2}
WIDTH=${3}
HEIGHT=${4}

scratchpad_show() {
    i3-msg "[con_mark=${I3_MARK}]" floating enable
    i3-msg "[con_mark=${I3_MARK}]" resize set ${WIDTH:=70} ppt ${HEIGHT:=80} ppt
    i3-msg "[con_mark=${I3_MARK}]" sticky enable
    i3-msg "[con_mark=${I3_MARK}]" scratchpad show
}

i3-msg fullscreen disable &

# try showing the scratchpad window
if ! scratchpad_show; then
    # if there is no such window...

    # launch the application.
    eval "${LAUNCH_CMD}" &

    # Wait for the next window event.
    i3-msg -t subscribe  '[ "window" ]'

    # Set a mark
    i3-msg mark ${I3_MARK}

    # Move it to the scratchpad workspace
    i3-msg move scratchpad

    # show the scratchpad window
    scratchpad_show

    # move window to the center of the screen
    i3-msg "[con_mark=${I3_MARK}]" move position center
fi
