#!/usr/bin/env bash

# Rerun the kmonad script whenever a new input device is added.

kmoinit() {
	config="$HOME/.config/kmonad/kmonad.kbd"
	keyb1="/dev/input/by-path/platform-i8042-serio-0-event-kbd"
	keyb2="/dev/input/by-id/usb-Lenovo_ThinkPad_Compact_USB_Keyboard_with_TrackPoint-event-kbd"
	keyb3="/dev/input/by-id/usb-Razer_Razer_BlackWidow_Tournament_Edition-event-kbd"
	keyb4="/dev/input/by-id/usb-SEMICO_USB_Gaming_Keyboard-event-kbd"
	killall kmonad
	sleep 0.1

	for keyboard in $keyb1 $keyb2 $keyb3 $keyb4; do
		if test -e "$keyboard"; then
			dest="/tmp/kmonad.kbd"
			cp "$config" $dest
			sed -i 's:keyboard_name:'$keyboard':' $dest
			setsid -f kmonad $dest
		fi
		sleep 0.1
	done
}
sleep 0.1

while :; do
	kmoinit
	grep -qP -m1 '[^un]bind.+\/[^:]+\(usb\)' <(udevadm monitor -u -t seat -s input -s usb)
done
