#!/bin/sh

if envycontrol --query | grep nvidia; then
	xrandr --setprovideroutputsource modesetting NVIDIA-0
	xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 144.00 \
		--output eDP-1-1 --left-of HDMI-0 --auto
else
	xrandr --output HDMI-1-0 --primary --auto \
		--output eDP1 --auto --left-of HDMI-1-0
fi

# xrandr --dpi 141 --fb 3969x2232 \
# 	--output eDP1 --primary --mode 1920x1080 \
# 	--output HDMI-1-0 --set "PRIME Synchronization" 1 \
# 	--scale 1.5x1.5 --pos 1920x0 --panning 2049x1152+1920+0
