#!/bin/sh

if envycontrol --query | grep nvidia; then
	xrandr --setprovideroutputsource modesetting NVIDIA-0
	xrandr --output eDP-1-1 --primary --auto \
		--output HDMI-0 --auto --right-of eDP-1-1
else
	xrandr --output eDP1 --primary --auto \
		--output HDMI-1-0 --auto --right-of eDP1 --set "PRIME Synchronization" 1
fi

# xrandr --dpi 141 --fb 3969x2232 \
# 	--output eDP1 --primary --mode 1920x1080 \
# 	--output HDMI-1-0 --set "PRIME Synchronization" 1 \
# 	--scale 1.5x1.5 --pos 1920x0 --panning 2049x1152+1920+0
