#!/bin/sh

if [ "$(uname -n)" = "skynet" ]; then

	if envycontrol --query | grep nvidia; then
		xrandr --setprovideroutputsource modesetting NVIDIA-0
		xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 144.00 \
			--output eDP1 --left-of HDMI-0 --auto
	else
		xrandr --output HDMI-1-0 --primary --auto \
			--output eDP1 --auto --left-of HDMI-1-0
	fi

elif [ "$(uname -n)" = "ArchKeith" ]; then
  xrandr --output eDP1 --primary --auto \
    --output DP2-1 --auto --left-of eDP1

elif [ "$(uname -n)" = "gpdskynet" ]; then
	xrandr --output DisplayPort-2 --primary --mode 1920x1080 --rate 165.00 --set TearFree on \
			--output DSI-1-1 --auto --right-of DisplayPort-2 --rotate right
fi

# xrandr --dpi 141 --fb 3969x2232 \
# 	--output eDP1 --primary --mode 1920x1080 \
# 	--output HDMI-1-0 --set "PRIME Synchronization" 1 \
# 	--scale 1.5x1.5 --pos 1920x0 --panning 2049x1152+1920+0
