#!/usr/bin/env sh

# vim-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Homepage: https://www.github.com/cknadler/vim-anywhere
#
# Open a temporary file with Vim. Once Vim is closed, copy the contents of that
# file to the system clipboard.

TMPFILE=/tmp/nvim-everywhere
xclip -o -selection clipboard >"$TMPFILE"

# Linux
# chmod o-r $TMPFILE # Make file only readable by you
tdropper -n everywhere "$TERMINAL" --class Everywhere -e nvim -c "set ft=markdown" "$TMPFILE"

xclip -i -selection clipboard "$TMPFILE"
