#!/bin/sh

rotdir "$@" | grep -i "\.\(png\|jpg\|jpeg\|gif\|webp\|tif\|ico\)\(_large\)*$" |
	setsid -f nsxiv -aio 2>/dev/null | while read -r file; do
	[ -z "$file" ] && continue
	lf -remote "send select \"$file\""
	lf -remote "send toggle"
done &
