/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package xmobar-0.41 */
#ifndef VERSION_xmobar
#define VERSION_xmobar "0.41"
#endif /* VERSION_xmobar */
#ifndef MIN_VERSION_xmobar
#define MIN_VERSION_xmobar(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  41 || \
  (major1) == 0 && (major2) == 41 && (minor) <= 0)
#endif /* MIN_VERSION_xmobar */

/* package X11-1.10.2 */
#ifndef VERSION_X11
#define VERSION_X11 "1.10.2"
#endif /* VERSION_X11 */
#ifndef MIN_VERSION_X11
#define MIN_VERSION_X11(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  10 || \
  (major1) == 1 && (major2) == 10 && (minor) <= 2)
#endif /* MIN_VERSION_X11 */

/* package async-2.2.4 */
#ifndef VERSION_async
#define VERSION_async "2.2.4"
#endif /* VERSION_async */
#ifndef MIN_VERSION_async
#define MIN_VERSION_async(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_async */

/* package base-4.14.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_base */

/* package containers-0.6.5.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.5.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_VERSION_containers */

/* package directory-1.3.6.0 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.6.0"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_directory */

/* package filepath-1.4.2.1 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.1"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */

/* package parsec-3.1.14.0 */
#ifndef VERSION_parsec
#define VERSION_parsec "3.1.14.0"
#endif /* VERSION_parsec */
#ifndef MIN_VERSION_parsec
#define MIN_VERSION_parsec(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 14)
#endif /* MIN_VERSION_parsec */

/* package unix-2.7.2.2 */
#ifndef VERSION_unix
#define VERSION_unix "2.7.2.2"
#endif /* VERSION_unix */
#ifndef MIN_VERSION_unix
#define MIN_VERSION_unix(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  7 || \
  (major1) == 2 && (major2) == 7 && (minor) <= 2)
#endif /* MIN_VERSION_unix */

/* package xmobar-0.41 */
#ifndef VERSION_xmobar
#define VERSION_xmobar "0.41"
#endif /* VERSION_xmobar */
#ifndef MIN_VERSION_xmobar
#define MIN_VERSION_xmobar(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  41 || \
  (major1) == 0 && (major2) == 41 && (minor) <= 0)
#endif /* MIN_VERSION_xmobar */

/* tool alex-3.2.6 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.2.6"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_alex */

/* tool c2hs-0.28.8 */
#ifndef TOOL_VERSION_c2hs
#define TOOL_VERSION_c2hs "0.28.8"
#endif /* TOOL_VERSION_c2hs */
#ifndef MIN_TOOL_VERSION_c2hs
#define MIN_TOOL_VERSION_c2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  28 || \
  (major1) == 0 && (major2) == 28 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_c2hs */

/* tool gcc-11.1.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11.1.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  1 || \
  (major1) == 11 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool happy-1.20.0 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.20.0"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_happy */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-1.8.0 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.8.0"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.10.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.36 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.36"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  36 || \
  (major1) == 2 && (major2) == 36 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "xmobar-0.41-IwkpCPIcySBGBnDzpoiXIX-xmobar"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.41"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
