#!/usr/bin/bash

hc() {
	herbstclient "$@"
}

hc emit_hook reload

# xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# REMOVE ALL EXISTING KEYBINDINGS #
#---------------------------------#
hc keyunbind --all

# KEYBINDINGS #
#-------------#
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4 # Use the super key as the main modifier

# System controls #
#-----------------#
hc keybind $Mod-Shift-c spawn kitty -T logout -e herbst-logout.sh
hc keybind $Mod-Control-r reload
hc keybind $Mod-q close_or_remove
hc keybind $Mod-Return spawn "${TERMINAL:-kitty}" #

# focusing client #
#-----------------#s
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right

hc keybind $Mod-h focus left
hc keybind $Mod-j cycle_all 1
hc keybind $Mod-k cycle_all -1
hc keybind $Mod-l focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# splitting frames #
#------------------#
hc keybind $Mod-u split bottom 0.6
hc keybind $Mod-o split right 0.6

# let the current frame explode into subframes #
#----------------------------------------------#
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients #
#--------------------------------------#
resizestep=0.02
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep
hc keybind $Mod-Control-Left resize left +$resizestep
hc keybind $Mod-Control-Down resize down +$resizestep
hc keybind $Mod-Control-Up resize up +$resizestep
hc keybind $Mod-Control-Right resize right +$resizestep

# tags #
#------#
tag_names=(一 二 三 四 五 六 七 八 九)
tag_keys=({1..9} 0)

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}"; do
	hc add "${tag_names[$i]}"
	hc set_layout grid
	hc set default_frame_layout 1
	key="${tag_keys[$i]}"
	if [ -n "$key" ]; then
		# first check if the tag is locked to some monitor.
		# if so, first focus the monitor
		hc keybind "$Mod-$key" \
			chain , silent substitute M tags."$i".my_monitor \
			focus_monitor M \
			, use_index "$i"
		hc keybind "$Mod-Shift-$key" move_index "$i"
	fi
done

# layouting #
#-----------#
hc keybind $Mod-Alt-s spawn new-layout.sh
hc keybind $Mod-Alt-l spawn ./.local/scripts/load-layout.sh
hc keybind $Mod-r remove
hc keybind $Mod-f spawn ~/.config/herbstluftwm/sc/maximize
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
# hc keybind $Mod-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-Shift-space \
	or , and . compare tags.focus.curframe_wcount = 2 \
	. cycle_layout +1 vertical horizontal max vertical grid \
	, cycle_layout +1

# focus #
#-------#
# hc keybind $Mod-BackSpace cycle_monitor
hc keybind $Mod-w cycle_monitor
# hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# MOUSE #
#-------#
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# RULES #
#-------#
hc unrule -F

# MONITORS #
#----------#
hc detect_monitors
hc set focus_crosses_monitor_boundaries true
hc set swap_monitors_to_get_tag false

# Lock current tag in the monitor
herbstclient keybind $Mod-t chain \
	, new_attr string tags.focus.my_monitor \
	, substitute M monitors.focus.index set_attr tags.focus.my_monitor M \
	, try and \
	. compare monitors.focus.name != "" \
	. substitute M monitors.focus.name \
	set_attr tags.focus.my_monitor M

# Add a keybinding for removing the lock
herbstclient keybind $Mod-Shift-t \
	remove_attr tags.focus.my_monitor

# Statically define which tag should be send to which monitor
lock_tag_to_monitor() {
	herbstclient chain \
		, new_attr string tags.by-name."$1".my_monitor \
		, set_attr tags.by-name."$1".my_monitor "$2"
}
# Already lock some of the tags to a monitor, for example:
# lock the second tag to the monitor with index 0
lock_tag_to_monitor 5 1

# THEME #
#-------#

THEME="$HOME/.config/herbstluftwm/themes/theme"
COLOR="$HOME/.config/herbstluftwm/themes/colors"
[ -f "$THEME" ] && . $THEME
[ -f "$COLOR" ] && . $COLOR

# MENUS #
#-------#
hc rule title~'launch.sh' floating=on floatplacement=center floating_geometry=600x800
hc rule title~'vsp2' floating=on floatplacement=center floating_geometry=375x1000
hc rule title~'configs' floating=on floatplacement=center floating_geometry=375x600
hc rule title~'windows' floating=on floatplacement=center floating_geometry=600x300
hc rule title~'logout' floating=on floatplacement=center floating_geometry=320x200
hc rule title~'vmach.sh' floating=on floatplacement=center floating_geometry=375x500

# CLASSES #
#---------#
hc rule class~'firefox' tag="${tag_names[0]}"
hc rule class~'Chromium' tag="${tag_names[1]}"

# SCRATCHPADS #
#-------------#
hc rule title~'scratchpad' floating=on floatplacement=center floating_geometry=1000x500
hc rule title~'FM' floating=on floatplacement=center floating_geometry=1000x800
hc rule class~'qutebrowser' floating=on floatplacement=center floating_geometry=1800x1000
hc rule title~'Mail' floating=on floatplacement=center floating_geometry=1500x800
hc rule title~'Music' floating=on floatplacement=center floating_geometry=1200x800
hc rule title~'Calc' floating=on floatplacement=center floating_geometry=1720x650

hc rule focus=on # normally focus new clients
hc rule floatplacement=center
#hc rule float_geometry=250x100
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on floatplacement=center
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# UNLOCK #
#--------#
hc unlock

# FIND THE PANEL #
#----------------#
panel=~/.config/polybar/launch.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1); do
	# start it on each monitor
	"$panel" "$monitor" &
done
hc split vertical 0.6
hc remove
