#!/bin/sh
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u $USER)/bus
export DISPLAY=:0

/usr/bin/notify-send -i ~/.config/dunst/images/heart.png "Health" "Fix your posture!\n
You don't want to end up crooked, do you?"
