#!/bin/sh
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u $USER)/bus
export DISPLAY=:0

/usr/bin/notify-send -i ~/.config/dunst/images/heart.png "Health" "Look after your eyes!\n
Look at something at a distance of 20 feet for a while or take a break!"
