reload "user.options"
reload "user.autocommands"
reload "user.keymaps"

reload "user.plugins"

reload "user.filetype"
reload "user.treesitter"
reload "user.lualine"
reload "user.lsp"
reload "user.inlay-hints"
reload "user.whichkey"
reload "user.colorizer"
reload "user.telescope"
reload "user.tmux"
reload "user.true-zen"
reload "user.surround"
-- reload "user.neoscroll"
reload "user.smoothie"
